const { contextBridge, ipcRenderer } = require('electron')

contextBridge.exposeInMainWorld('overheadDesktop', {
  onSecurityLock: (callback) => {
    const listener = () => callback()
    ipcRenderer.on('security-lock', listener)
    return () => ipcRenderer.removeListener('security-lock', listener)
  },
  onMicrosoftDeviceCode: (callback) => {
    const listener = (_event, details) => callback(details)
    ipcRenderer.on('microsoft-device-code', listener)
    return () => ipcRenderer.removeListener('microsoft-device-code', listener)
  },
  integrityReport: () => ipcRenderer.invoke('integrity-report'),
  powerCycle: () => ipcRenderer.invoke('app:power-cycle'),
})

contextBridge.exposeInMainWorld('overheadBackend', {
  bootstrap: () => ipcRenderer.invoke('backend:bootstrap'),
  health: () => ipcRenderer.invoke('backend:health'),
  register: (payload) => ipcRenderer.invoke('auth:register', payload),
  registerCustomerAccess: (payload) => ipcRenderer.invoke('auth:register-customer', payload),
  signIn: (payload) => ipcRenderer.invoke('auth:sign-in', payload),
  rememberedSignIn: () => ipcRenderer.invoke('auth:remembered-sign-in'),
  resumeSession: () => ipcRenderer.invoke('auth:resume-session'),
  verifyEmail: (payload) => ipcRenderer.invoke('auth:verify-email', payload),
  lockSession: (sessionId) => ipcRenderer.invoke('session:lock', sessionId),
  listCustomers: () => ipcRenderer.invoke('customers:list'),
  listTasks: () => ipcRenderer.invoke('tasks:list'),
  updateTaskStatus: (payload) => ipcRenderer.invoke('tasks:update-status', payload),
  queueWorkflowJob: (payload) => ipcRenderer.invoke('jobs:queue', payload),
  processDueJobs: () => ipcRenderer.invoke('jobs:process-due'),
  listWorkflowJobs: () => ipcRenderer.invoke('jobs:list'),
  createCustomer: (payload) => ipcRenderer.invoke('customers:create', payload),
  selectDocumentFile: () => ipcRenderer.invoke('documents:select-file'),
  attachCustomerDocument: (payload) => ipcRenderer.invoke('documents:attach', payload),
  openCustomerDocument: (documentId) => ipcRenderer.invoke('documents:open', documentId),
  createCustomerPortalInvite: (payload) => ipcRenderer.invoke('customers:create-portal-invite', payload),
  createAppointment: (payload) => ipcRenderer.invoke('appointments:create', payload),
  createQuote: (payload) => ipcRenderer.invoke('quotes:create', payload),
  createInvoice: (payload) => ipcRenderer.invoke('invoices:create', payload),
  assignOperationalCustomer: (payload) => ipcRenderer.invoke('operations:assign-customer', payload),
  updateOperationalStatus: (payload) => ipcRenderer.invoke('operations:update-status', payload),
  connectMicrosoft: (payload) => ipcRenderer.invoke('microsoft:connect', payload),
  listMicrosoftConnections: () => ipcRenderer.invoke('microsoft:list-connections'),
  previewMicrosoftImport: (payload) => ipcRenderer.invoke('microsoft:preview-import', payload),
  importMicrosoftPreview: (payload) => ipcRenderer.invoke('microsoft:import-preview', payload),
  applyCustomerPlaybook: (payload) => ipcRenderer.invoke('playbooks:apply', payload),
  buildGuidedLaunchPlan: () => ipcRenderer.invoke('guided-launch:build'),
  acknowledgeLegal: (payload) => ipcRenderer.invoke('legal:acknowledge', payload),
  listFraudSignals: () => ipcRenderer.invoke('fraud:list'),
  stripeAuthorizationUrl: () => ipcRenderer.invoke('stripe:authorization-url'),
  openStripeAuthorization: () => ipcRenderer.invoke('stripe:open-authorization'),
  saveStripeConnection: (payload) => ipcRenderer.invoke('stripe:save-connection', payload),
  listStripeConnections: () => ipcRenderer.invoke('stripe:list-connections'),
  importStripeSnapshot: (payload) => ipcRenderer.invoke('stripe:import-snapshot', payload),
  listStripeImports: () => ipcRenderer.invoke('stripe:list-imports'),
  listPaymentRecords: () => ipcRenderer.invoke('payments:list-records'),
  squareAuthorizationUrl: () => ipcRenderer.invoke('square:authorization-url'),
  openSquareAuthorization: () => ipcRenderer.invoke('square:open-authorization'),
  saveSquareConnection: (payload) => ipcRenderer.invoke('square:save-connection', payload),
  importSquareSnapshot: (payload) => ipcRenderer.invoke('square:import-snapshot', payload),
  listSquareConnections: () => ipcRenderer.invoke('square:list-connections'),
  listSquareImports: () => ipcRenderer.invoke('square:list-imports'),
  createEmbeddedCheckout: (payload) => ipcRenderer.invoke('billing:create-embedded-checkout', payload),
  startFreeGoldTrial: () => ipcRenderer.invoke('billing:start-free-gold-trial'),
  cancelSubscriptionWithUnusedTimeRefund: () => ipcRenderer.invoke('billing:cancel-with-unused-time-refund'),
  getRemoteEntitlements: () => ipcRenderer.invoke('billing:get-entitlements'),
  getRemoteBillingActivity: () => ipcRenderer.invoke('billing:get-activity'),
  getEntitlements: () => ipcRenderer.invoke('entitlements:get'),
  saveBillingProfile: (payload) => ipcRenderer.invoke('billing:save-profile', payload),
  listBillingProfiles: () => ipcRenderer.invoke('billing:list-profiles'),
  listUsers: () => ipcRenderer.invoke('users:list'),
  createStaffAccount: (payload) => ipcRenderer.invoke('users:create-staff', payload),
  updateUser: (payload) => ipcRenderer.invoke('users:update', payload),
  listLicenses: () => ipcRenderer.invoke('licenses:list'),
  refreshUserLicense: (payload) => ipcRenderer.invoke('licenses:refresh-user', payload),
  listEmployeeLicenses: () => ipcRenderer.invoke('employee-licenses:list'),
  createEmployeeLicense: (payload) => ipcRenderer.invoke('employee-licenses:create', payload),
  updateEmployeeLicense: (payload) => ipcRenderer.invoke('employee-licenses:update', payload),
  createApprovalRequest: (payload) => ipcRenderer.invoke('approvals:create', payload),
  decideApprovalRequest: (payload) => ipcRenderer.invoke('approvals:decide', payload),
  listApprovalRequests: () => ipcRenderer.invoke('approvals:list'),
  resetPassword: (payload) => ipcRenderer.invoke('auth:reset-password', payload),
  updateToggle: (payload) => ipcRenderer.invoke('toggles:update', payload),
  createSupportTicket: (payload) => ipcRenderer.invoke('support:create-ticket', payload),
  listSharedSupportTickets: () => ipcRenderer.invoke('support:list-shared-tickets'),
  officeChecklist: () => ipcRenderer.invoke('office:checklist'),
  createQuickNote: (payload) => ipcRenderer.invoke('notes:create', payload),
  createFillablePdf: (payload) => ipcRenderer.invoke('pdf:create-fillable', payload),
  createOperationalDocument: (payload) => ipcRenderer.invoke('pdf:create-operational', payload),
  createSubscriptionReceipt: () => ipcRenderer.invoke('billing:create-receipt'),
  createDataRequest: (payload) => ipcRenderer.invoke('compliance:create-data-request', payload),
  complianceSummary: () => ipcRenderer.invoke('compliance:summary'),
  listAuditEvents: (limit) => ipcRenderer.invoke('audit:list', limit),
  updateSetting: (payload) => ipcRenderer.invoke('settings:update', payload),
  createBackup: () => ipcRenderer.invoke('backup:create'),
  createDataExport: () => ipcRenderer.invoke('export:create'),
  validateRestorePackage: (filePath) => ipcRenderer.invoke('restore:validate', filePath),
  createSupportBundle: () => ipcRenderer.invoke('support:create-bundle'),
  updaterStatus: () => ipcRenderer.invoke('updater:status'),
  installDownloadedUpdate: () => ipcRenderer.invoke('updater:install'),
})
