export const customerDatabaseSchema = {
  schema: 'overhead-customers-v1',
  tables: {
    customers: [
      'id',
      'business_name',
      'owner_name',
      'email',
      'website',
      'industry',
      'timezone',
      'status',
      'service_area',
      'preferred_contact',
      'created_at',
      'updated_at',
    ],
    user_profiles: [
      'id',
      'customer_id',
      'name',
      'email',
      'role',
      'status',
      'recovery_hint',
      'last_sign_in',
      'created_at',
      'updated_at',
    ],
    sessions: [
      'id',
      'user_profile_id',
      'device_name',
      'lock_state',
      'started_at',
      'last_seen_at',
      'ended_at',
    ],
    access_events: [
      'id',
      'user_profile_id',
      'event_type',
      'device_name',
      'ip_hint',
      'risk_level',
      'created_at',
    ],
    workflow_preferences: [
      'customer_id',
      'booking_rules',
      'answer_tone',
      'quote_rules',
      'invoice_rules',
      'followup_rules',
      'human_review_required',
    ],
    admin_state: [
      'customer_id',
      'open_tasks',
      'last_booking_request',
      'last_quote_sent',
      'last_invoice_sent',
      'next_followup_due',
      'risk_status',
    ],
    compliance_profile: [
      'customer_id',
      'terms_accepted_at',
      'privacy_accepted_at',
      'acceptable_use_accepted_at',
      'ai_disclosure_accepted_at',
      'data_retention_days',
      'export_allowed',
      'delete_requested_at',
    ],
    legal_documents: [
      'id',
      'title',
      'version',
      'status',
      'body',
      'effective_at',
      'updated_at',
    ],
    support_tickets: [
      'id',
      'customer_id',
      'subject',
      'priority',
      'status',
      'details',
      'diagnostic_bundle_path',
      'created_at',
      'updated_at',
    ],
    feature_entitlements: [
      'id',
      'customer_id',
      'feature_name',
      'category',
      'enabled',
      'plan',
      'updated_at',
    ],
    audit_events: [
      'id',
      'customer_id',
      'event_type',
      'title',
      'details',
      'checksum',
      'created_at',
    ],
    protected_evidence: [
      'id',
      'customer_id',
      'title',
      'evidence_type',
      'classification',
      'masked_by_default',
      'checksum',
      'created_at',
    ],
    tamper_events: [
      'id',
      'event_type',
      'severity',
      'file_path',
      'expected_hash',
      'observed_hash',
      'details',
      'created_at',
    ],
    integrity_snapshots: [
      'id',
      'snapshot_type',
      'app_version',
      'file_manifest',
      'signature_status',
      'created_at',
    ],
  },
}

export const sampleCustomers = [
  {
    id: 'oh-cust-001',
    business_name: 'Oak City Detail',
    owner_name: 'Jordan Miles',
    email: 'owner@oakcity.example',
    website: 'https://oakcity.example',
    industry: 'Auto detailing',
    timezone: 'America/New_York',
    status: 'Active setup',
    service_area: 'Raleigh, Cary, Knightdale',
    preferred_contact: 'Email',
    workflow_preferences: {
      booking_rules: 'Require service type, vehicle size, address, date window, and deposit status.',
      answer_tone: 'Direct, polite, short. Escalate pricing exceptions to owner.',
      quote_rules: 'Use base package, add pet hair, heavy soil, mobile travel, and ceramic add-ons.',
      invoice_rules: 'Send invoice after service completion. Remind at day 3 and day 7 if unpaid.',
      followup_rules: 'Send review request after paid invoice. Send maintenance reminder after 30 days.',
      human_review_required: true,
    },
    admin_state: {
      open_tasks: 6,
      last_booking_request: '2026-07-18 09:30:00',
      last_quote_sent: '2026-07-17 15:20:00',
      last_invoice_sent: '2026-07-16 11:10:00',
      next_followup_due: '2026-07-19 10:00:00',
      risk_status: 'Normal',
    },
    compliance_profile: {
      terms_accepted_at: '',
      privacy_accepted_at: '',
      acceptable_use_accepted_at: '',
      ai_disclosure_accepted_at: '',
      data_retention_days: 365,
      export_allowed: true,
      delete_requested_at: '',
    },
  },
]
